--------------------------------------------------------
--  File created - Friday-December-18-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AUTHENTIFICATION
--------------------------------------------------------

  CREATE TABLE "TPJAVA"."AUTHENTIFICATION" 
   (	"USERNAME" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(50 BYTE), 
	"CIN" VARCHAR2(8 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMPTE
--------------------------------------------------------

  CREATE TABLE "TPJAVA"."COMPTE" 
   (	"CIN" VARCHAR2(8 BYTE), 
	"IDCOMPTE" VARCHAR2(50 BYTE), 
	"RIB" VARCHAR2(50 BYTE), 
	"MDP" VARCHAR2(50 BYTE), 
	"TYPECOMPTE" VARCHAR2(50 BYTE), 
	"SOLDE" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PERSONNE
--------------------------------------------------------

  CREATE TABLE "TPJAVA"."PERSONNE" 
   (	"CIN" VARCHAR2(8 BYTE), 
	"NOM" VARCHAR2(50 BYTE), 
	"PRENOM" VARCHAR2(50 BYTE), 
	"SEXE" VARCHAR2(50 BYTE), 
	"DATENAISS" VARCHAR2(20 BYTE), 
	"NUMTEL" VARCHAR2(8 BYTE), 
	"VILLE" VARCHAR2(50 BYTE), 
	"ADRESSE" VARCHAR2(50 BYTE), 
	"CODE_POSTAL" VARCHAR2(50 BYTE), 
	"GOUVERNERAT" VARCHAR2(50 BYTE), 
	"STATUT_SOCIAL" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TRANSACTION
--------------------------------------------------------

  CREATE TABLE "TPJAVA"."TRANSACTION" 
   (	"CIN" VARCHAR2(8 BYTE), 
	"IDCOMPTE" VARCHAR2(50 BYTE), 
	"IDTRANSACTION" VARCHAR2(50 BYTE), 
	"TYPE" VARCHAR2(50 BYTE), 
	"DATE_T" VARCHAR2(20 BYTE), 
	"AMOUNT" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VIREMENT
--------------------------------------------------------

  CREATE TABLE "TPJAVA"."VIREMENT" 
   (	"IDVIREMENT" VARCHAR2(50 BYTE), 
	"DATEV" VARCHAR2(20 BYTE), 
	"CINEMM" VARCHAR2(8 BYTE), 
	"IDCOMPTEEMM" VARCHAR2(50 BYTE), 
	"CINACC" VARCHAR2(8 BYTE), 
	"IDCOMPTEACC" VARCHAR2(50 BYTE), 
	"AMOUNT" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007605
--------------------------------------------------------

  CREATE UNIQUE INDEX "TPJAVA"."SYS_C007605" ON "TPJAVA"."AUTHENTIFICATION" ("USERNAME", "PASSWORD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007606
--------------------------------------------------------

  CREATE UNIQUE INDEX "TPJAVA"."SYS_C007606" ON "TPJAVA"."AUTHENTIFICATION" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007589
--------------------------------------------------------

  CREATE UNIQUE INDEX "TPJAVA"."SYS_C007589" ON "TPJAVA"."COMPTE" ("CIN", "IDCOMPTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007590
--------------------------------------------------------

  CREATE UNIQUE INDEX "TPJAVA"."SYS_C007590" ON "TPJAVA"."COMPTE" ("RIB") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007584
--------------------------------------------------------

  CREATE UNIQUE INDEX "TPJAVA"."SYS_C007584" ON "TPJAVA"."PERSONNE" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007585
--------------------------------------------------------

  CREATE UNIQUE INDEX "TPJAVA"."SYS_C007585" ON "TPJAVA"."PERSONNE" ("NUMTEL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007593
--------------------------------------------------------

  CREATE UNIQUE INDEX "TPJAVA"."SYS_C007593" ON "TPJAVA"."TRANSACTION" ("CIN", "IDCOMPTE", "IDTRANSACTION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007601
--------------------------------------------------------

  CREATE UNIQUE INDEX "TPJAVA"."SYS_C007601" ON "TPJAVA"."VIREMENT" ("IDVIREMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table AUTHENTIFICATION
--------------------------------------------------------

  ALTER TABLE "TPJAVA"."AUTHENTIFICATION" ADD UNIQUE ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TPJAVA"."AUTHENTIFICATION" ADD PRIMARY KEY ("USERNAME", "PASSWORD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TPJAVA"."AUTHENTIFICATION" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMPTE
--------------------------------------------------------

  ALTER TABLE "TPJAVA"."COMPTE" ADD UNIQUE ("RIB")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TPJAVA"."COMPTE" ADD PRIMARY KEY ("CIN", "IDCOMPTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TPJAVA"."COMPTE" MODIFY ("TYPECOMPTE" NOT NULL ENABLE);
  ALTER TABLE "TPJAVA"."COMPTE" MODIFY ("MDP" NOT NULL ENABLE);
  ALTER TABLE "TPJAVA"."COMPTE" MODIFY ("RIB" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSONNE
--------------------------------------------------------

  ALTER TABLE "TPJAVA"."PERSONNE" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "TPJAVA"."PERSONNE" ADD UNIQUE ("NUMTEL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TPJAVA"."PERSONNE" ADD PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TPJAVA"."PERSONNE" MODIFY ("STATUT_SOCIAL" NOT NULL ENABLE);
  ALTER TABLE "TPJAVA"."PERSONNE" MODIFY ("GOUVERNERAT" NOT NULL ENABLE);
  ALTER TABLE "TPJAVA"."PERSONNE" MODIFY ("CODE_POSTAL" NOT NULL ENABLE);
  ALTER TABLE "TPJAVA"."PERSONNE" MODIFY ("ADRESSE" NOT NULL ENABLE);
  ALTER TABLE "TPJAVA"."PERSONNE" MODIFY ("VILLE" NOT NULL ENABLE);
  ALTER TABLE "TPJAVA"."PERSONNE" MODIFY ("NUMTEL" NOT NULL ENABLE);
  ALTER TABLE "TPJAVA"."PERSONNE" MODIFY ("SEXE" NOT NULL ENABLE);
  ALTER TABLE "TPJAVA"."PERSONNE" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "TPJAVA"."PERSONNE" MODIFY ("NOM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRANSACTION
--------------------------------------------------------

  ALTER TABLE "TPJAVA"."TRANSACTION" ADD PRIMARY KEY ("CIN", "IDCOMPTE", "IDTRANSACTION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TPJAVA"."TRANSACTION" MODIFY ("DATE_T" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VIREMENT
--------------------------------------------------------

  ALTER TABLE "TPJAVA"."VIREMENT" ADD PRIMARY KEY ("IDVIREMENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TPJAVA"."VIREMENT" MODIFY ("IDCOMPTEACC" NOT NULL ENABLE);
  ALTER TABLE "TPJAVA"."VIREMENT" MODIFY ("CINACC" NOT NULL ENABLE);
  ALTER TABLE "TPJAVA"."VIREMENT" MODIFY ("IDCOMPTEEMM" NOT NULL ENABLE);
  ALTER TABLE "TPJAVA"."VIREMENT" MODIFY ("CINEMM" NOT NULL ENABLE);
  ALTER TABLE "TPJAVA"."VIREMENT" MODIFY ("DATEV" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table AUTHENTIFICATION
--------------------------------------------------------

  ALTER TABLE "TPJAVA"."AUTHENTIFICATION" ADD FOREIGN KEY ("CIN")
	  REFERENCES "TPJAVA"."PERSONNE" ("CIN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMPTE
--------------------------------------------------------

  ALTER TABLE "TPJAVA"."COMPTE" ADD FOREIGN KEY ("CIN")
	  REFERENCES "TPJAVA"."PERSONNE" ("CIN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRANSACTION
--------------------------------------------------------

  ALTER TABLE "TPJAVA"."TRANSACTION" ADD FOREIGN KEY ("CIN", "IDCOMPTE")
	  REFERENCES "TPJAVA"."COMPTE" ("CIN", "IDCOMPTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VIREMENT
--------------------------------------------------------

  ALTER TABLE "TPJAVA"."VIREMENT" ADD FOREIGN KEY ("CINEMM", "IDCOMPTEEMM")
	  REFERENCES "TPJAVA"."COMPTE" ("CIN", "IDCOMPTE") ENABLE;
  ALTER TABLE "TPJAVA"."VIREMENT" ADD FOREIGN KEY ("CINACC", "IDCOMPTEACC")
	  REFERENCES "TPJAVA"."COMPTE" ("CIN", "IDCOMPTE") ENABLE;
